production_job:
  stage: deploy
  only:
    - main # Run this job only on changes to main branch

  before_script:
    # Generate ssh key
    - mkdir -p ~/.ssh
    - echo -e "$prod_ssh" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f/.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - bash .gitlab-deploy-prod.sh

  environment:

    name: production
    url: https://www.travisbridle.com

  stage_job:
    stage: deploy
    only: 
      - stage # Runs this job only on changes for the stage branch
    
  before_script:
  # Generate ssh key
  - mkdir -p ~/.ssh
  - echo -e "$stage_ssh" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f/.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - bash.gitlab-deploy-stage.sh
  
  environment:
    name: stage
    url: https://www-stage.travisbridle.com