version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            echo "Installing packages"
            #install curl
            - sudo yum -y install curl
            #install node12
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            - . ~/.nvm/nvm.sh
            - nvm install node
            - node -e "console.log('Running Node.js ' + process.version)"
            #install yarn
            - curl -o- -L https://yarnpkg.com/install.sh | bash
            - source ~/.bashrc
            - yum install --no-install-recommends yard
    pre_build:
        commands: 
            - #install dependencies
            - echo "installing dependancies"
            - yarn
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests on yarn"
            - yarn test
            - echo "Building..."
            - yarn build
    artifacts:
      files:
        - "**/*"
      discard-paths: no 
      base-directory: /
    post_build:
        commands:
            - echo "we are in the post build phase"
            

            