version: 0.2
phases:
  pre_build:
    commands:
      - echo Entered the install phase...
      - npm install --global lerna 
      - lerna bootstrap --concurrency=1 -- --production
  build:
    commands:
      - npm run build
artifacts:
  baseDirectories: build
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*